# Generated by Django 3.2 on 2021-05-02 12:09

import application.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('userId', models.IntegerField(verbose_name=10)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=10)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('my_file', models.FileField(blank=True, upload_to='doc', validators=[application.models.validate_document, django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
            ],
            options={
                'db_table': 'upload',
            },
        ),
    ]
